IF(WIN32)
  FIND_LIBRARY(UUID_LIBRARY NAMES Rpcrt4 PATH)

  IF(UUID_LIBRARY)
    SET(UUID_FOUND TRUE)
  ENDIF(UUID_LIBRARY)

ELSE()
  FIND_PATH(UUID_INCLUDE_DIR uuid/uuid.h)
  FIND_LIBRARY(UUID_LIBRARY NAMES uuid PATH)

  IF(UUID_INCLUDE_DIR)
    SET(UUID_FOUND TRUE)
  ENDIF(UUID_INCLUDE_DIR)

  IF(NOT UUID_LIBRARY)
    SET(UUID_LIBRARY "")
  ENDIF(NOT UUID_LIBRARY)

ENDIF(WIN32)

IF(NOT UUID_FOUND)
  IF(UUID_FIND_REQUIRED)
    IF(WIN32)
      MESSAGE(FATAL_ERROR "Could not find Rpcrt4")
    ELSE()
      MESSAGE(FATAL_ERROR "Could not find UUID")
    ENDIF(WIN32)
  ENDIF(UUID_FIND_REQUIRED)
ENDIF(NOT UUID_FOUND)
